name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: voidzero-dev/setup-vp@fd19e0626188613eec92a77e875180c6445b56ba # v1.2.0

      - name: Install dependencies
        run: vp install

      - name: Run CI
        run: npm run ci
